const input1 = [
  'Korma Jaya Utama',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Adinata',
  'Korma Jaya Utama',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Adinata',
  'Korma Jaya Utama',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Korma Jaya Utama',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Korma Jaya Utama',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Adinata',
  'Korma Jaya Utama',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Korma Jaya Utama',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood'
];
const input2 = [
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Adinata',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Adinata',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Korma Jaya Utama',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Adinata',
  'Korma Jaya Utama',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Korma Jaya Utama',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood'
];

const input3 = [
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Adinata',
  'Aneka Sari Food',
  'Sari Wangi',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Adinata',
  'Aneka Sari Food',
  'Sari Wangi',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Aneka Sari Food',
  'Sari Wangi',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Korma Jaya Utama',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Adinata',
  'Korma Jaya Utama',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood',
  'Korma Jaya Utama',
  'Aneka Sari Food',
  'Sari Wangi',
  'ABC',
  'ABC',
  'Cipta Rasa',
  'Sumber Rasa',
  'Damai',
  'Damai',
  'Arta Nusa',
  'Cipta Sari',
  'Indofood'
];

const countActiveCompany = (arr) => {
  const percentage = 8;
  const totalCount = arr.length;
  const limitCount = Math.ceil((percentage / 100) * totalCount);
  const mapArray = new Map();
  const resultActiveCompany = {
    total_data: 0,
    company_list: []
  };

  for (const arrValue of arr) {
    mapArray.set(arrValue, (mapArray.get(arrValue) || 0) + 1);
  }

  const tempActiveCompany = [];
  for (const [key, value] of mapArray) {
    if (value >= limitCount) tempActiveCompany.push(key);
  }

  resultActiveCompany.company_list = tempActiveCompany.sort();

  resultActiveCompany.total_data = resultActiveCompany.company_list.length;

  return resultActiveCompany;
};

console.log(countActiveCompany(input1));
console.log(countActiveCompany(input2));
console.log(countActiveCompany(input3));
